package dragon

import (
	"bytes"
	"testing"
)

func TestOut(t *testing.T) {
	libChan := make(chan lib)

	go func() {
		libChan <- lib{
			pkg:    "dragon",
			object: "Imports",
			path:   "github.com/monochromegane/dragon-imports",
		}
		close(libChan)
	}()

	expect := `// AUTO-GENERATED BY dragon-imports

package imports

var stdlib = map[string]string{
	"dragon.Imports": "github.com/monochromegane/dragon-imports",

	"unsafe.Alignof":       "unsafe",
	"unsafe.ArbitraryType": "unsafe",
	"unsafe.Offsetof":      "unsafe",
	"unsafe.Pointer":       "unsafe",
	"unsafe.Sizeof":        "unsafe",
}
`

	buf := &bytes.Buffer{}
	out(libChan, buf)
	if actual := buf.String(); actual != expect {
		t.Errorf("out should return\n%s\nbut\n%s", expect, actual)
	}
}
