package dragon

import "os"

func ExampleOut() {
	libChan := make(chan lib)
	done := make(chan struct{})

	go func() {
		libChan <- lib{
			pkg:    "dragon",
			object: "Imports",
			path:   "github.com/monochromegane/dragon-imports",
		}
		close(libChan)
	}()

	go out(libChan, done, os.Stdout)

	<-done

	// Output:
	// // AUTO-GENERATED BY dragon-imports
	//
	// package imports
	//
	// var stdlib = map[string]string{
	//	"dragon.Imports": "github.com/monochromegane/dragon-imports",
	// }
}
